# Generated by Django 5.1.4 on 2024-12-12 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0006_airport_closest_big_city"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="crews",
            new_name="crew",
        ),
    ]
