# Generated by Django 5.1.4 on 2024-12-12 03:38

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0007_rename_crews_flight_crew"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplanetype",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport.models.airplane_type_image_path
            ),
        ),
        migrations.AddField(
            model_name="airport",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport.models.airport_image_path
            ),
        ),
    ]
